container:
  default: 'docker://bsmith89/compbio2:5cbda6bd9437faaa46546c71b3a2afb961ba5376'
  toolz: 'docker://bsmith89/compbio2:5cbda6bd9437faaa46546c71b3a2afb961ba5376'
  gtpro: 'docker://bsmith89/gtpro:522c78fdbd1524580c636956a4cb5b1dc268d022'
  mambaforge: 'docker://condaforge/mambaforge:4.11.0-4'
proc: 'noop'
MAX_THREADS: 4
USE_CUDA: 0
ALL:
  - 'TODO'
